name: Build Python EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile your_script.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: your-exe
          path: dist/your_script.exe

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v4
        with:
          files: dist/your_script.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
