name: Build and Upload Python EXE

on:
  push:
    branches:
      - main  # Triggers on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use your preferred OS

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile main.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4  # Upload artifacts without requiring a tag
        with:
          name: main-exe
          path: dist/main.exe  # Path to your .exe file
