name: Build Python EXE

on:
  push:
    branches:
      - main
    tags:
      - 'v1.0.0'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile main.py  # Updated to use main.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-exe
          path: dist/main.exe

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
